### ISSUE TITLE
push通知用サーバー設計（外部サービス選定、ドキュメント作成）

### ISSUE THREAD

**Issue by rinrintaro** [rinrintaro/espetas_test#17]

**Comment by YuyaTerada** [comment]
"push通知用にサーバーをもう一つ用意
awsのsqsとlambdaを使うかGMCで自前で用意する。
識別IDを利用規約同意時に取得しDBに保存。これでプッシュが送れるようになる"	

識別トークンは端末が再起動した時にリフレッシュされるので、それを検知するクラスを作成しDBを更新する	

プッシュ通知が送れることを確認するのを優先度高めにやる

**Comment by YuyaTerada** [comment]
firebaseで両OS送れるようにできる

**Comment by YuyaTerada** [comment]
https://docs.google.com/a/espetas.com/document/d/1u1chcQ1tJS5BzMYSy1pCOhy5Rk_ftRbxiQRAk56Ging/edit?usp=sharing

まとめ資料
