### ISSUE TITLE
DBテーブル・カラム修正

### ISSUE THREAD

**Issue by YuyaTerada** [rinrintaro/espetas_test#21]
修正点が多いので一度DBも合わせる。

**Comment by YuyaTerada** [comment]
DB設計書修正
１，logsテーブル追加（DB修正済み）
２，authorizationテーブル、トークン名を変更（DB修正済み）
３，pinsテーブルを追加（DB修正済み）
４，favorite_advisersでお気に入り中かキャンセルしたかのステータスを追加（DB修正済み）
５，approved_questionsでテキストメモをロングテキストで追加。（DB修正済み）
６，callsのprice_per_minを廃止。twilio_chargeをnull許可。(DB修正済み）
７，stripe_currencyを追加（DB修正済み）
８，transactionsテーブルを修正（DB修正済み）
９、large_categoriesテーブルでnameをUQに。
　　small_categoriesにprice_per_minを追加。updated_atを追加（DB修正済み）
１０，Triggerの使いみち再考。ログ記録時、特定のテーブルのバックアップ用、小テーブルの内容が更新されたときに関連する親テーブルの情報を更新したいとき（開発時に弾さんに聞きつつ実装）
１１，questionsでstatusの値を追加（DB修正済み）
１２，マッピングテーブルなど大体のテーブルでIDとstatusが必要。（DB修正）
１３，created_at,updated_atを大体のテーブルに追加。（DB修正）
１４，ClientとAdviser両方登録するユーザ向けのアカウント状態管理を修正。advisersテーブルにもStripeなど基本情報をもたせる（DB修正済み）
１５，パスワードは別テーブルcredentialsテーブルに保存する。セキュリティ上。（DB修正済み）
１６，認証周りの修正。テーブルはAdviserとClientで全て分ける。（DB修正済み）
１７，マッピングテーブルの参照を変更する。（DB修正済み）

**Comment by rinrintaro** [comment]
１５、Adviserテーブルをusersの基本情報もたせた独立したテーブルに改修。
それに伴う他のテーブルも修正（修正完了）

**Comment by rinrintaro** [comment]
１６、機種情報のテーブル作成し、Signin時に新しい端末かどうか判別し、新しいものは登録
完了済み

**Comment by rinrintaro** [comment]
１７、ログインフロー変更＋認証方法変更（電話番号）によるDB設計書、機能一覧修正
